### ISSUE TITLE
Increase robustness: timeout/retry failed targets.

### ISSUE THREAD

**Issue by mrchypark** [wlandau-lilly/drake#76] opened 2017-08-28 17:45 UTC
# Troubleshooting

The "caution" vignette (`vignette("caution")`, also linked from the [CRAN page](https://CRAN.R-project.org/package=drake) under "vignettes") lists some known issues, limitations, and edge cases. Please look there first if you encounter problems or unexpected behavior. If that fails, please search the [issues page](https://github.com/wlandau-lilly/drake/issues), taking care to browse the closed issues as well. If you are still unsatisfied, please submit your bug report, question, or feature reqest as a [new issue](https://github.com/wlandau-lilly/drake/issues/new).

**Comment by wlandau-lilly** [comment] 2017-08-28 20:06
@mrchypark Is there anything I should do to make the troubleshooting directions more visible? Is there a specific error I can help you resolve?

**Comment by mrchypark** [comment] 2017-08-28 20:29
@wlandau-lilly  Thank you for your attention. I want to timeout option each task and auto rerun action.

When I use this package, I failed some tasks rarely and stop all process. 
Do I have only options running make function again?

**Comment by wlandau-lilly** [comment] 2017-08-28 21:04
@mrchypark Great point. If I am interpreting your suggestion correctly, that would certainly make `drake` workflows more resiliant. Right now, you have to rerun `make()`, as you say, or add special functionality to your workflow.

```r
timeout_and_try_again <- function(code, attempts = 1, timeout = Inf){
  # Try to run `code`
  # If the time limit is reached or the code fails, run it again until you run out of attempts.
}
library(drake)
load_basic_example()
my_plan$command <- paste(
  "timeout_and_try_again({",
  my_plan$command,
  "}, attempts = 5, timeout = 20)")
head(my_plan)
my_plan[1,]
##        target
## 1 'report.md'
##                                                                                             command
## 1 timeout_and_try_again({ my_knit('report.Rmd', report_dependencies) }, attempts = 5, timeout = 20)
```

I could think about building something like this into `drake` itself in future versions. At the moment, though, I am not sure how to best implement it. 

I also have some mild reproducibility concerns. If we allow timeouts and retries, will someone else really be able to run the same code and get the same result? If the code is prone to failure sometimes, are the results reproducible?

If you are scraping data from the web and the connection fails, then it makes perfect sense to timeout and retry. But in that case, you might be better off treating web datasets as imports rather than targets. That way, your workflow can react to changes in websites.

What is the goal of your workflow?

**Comment by wlandau-lilly** [comment] 2017-08-28 21:10
A simpler alternative, probably not exactly ideal: you already have the option of picking which targets to rerun (plus their dependencies).

```r
library(drake)
load_basic_example()
my_plan

##                    target                                      command
## 1             'report.md'   my_knit('report.Rmd', report_dependencies)
## 2                   small                                  simulate(5)
## 3                   large                                 simulate(50)
## 4     report_dependencies      c(small, large, coef_regression2_small)
## 5       regression1_small                                  reg1(small)
## 6       regression1_large                                  reg1(large)
## 7       regression2_small                                  reg2(small)
## 8       regression2_large                                  reg2(large)
## 9  summ_regression1_small suppressWarnings(summary(regression1_small))
## 10 summ_regression1_large suppressWarnings(summary(regression1_large))
## 11 summ_regression2_small suppressWarnings(summary(regression2_small))
## 12 summ_regression2_large suppressWarnings(summary(regression2_large))
## 13 coef_regression1_small                      coef(regression1_small)
## 14 coef_regression1_large                      coef(regression1_large)
## 15 coef_regression2_small                      coef(regression2_small)
## 16 coef_regression2_large                      coef(regression2_large)

make(my_plan, targets = "regression1_small")

## check 4 items
## import data.frame
## import rpois
## import stats::rnorm
## import lm
## check 2 items
## import simulate
## import reg1
## check 1 item
## target small
## check 1 item
## target regression1_small

cached()

## [1] "data.frame"        "lm"                "reg1"
## [4] "regression1_small" "rpois"             "simulate"
## [7] "small"             "stats::rnorm"
```

**Comment by mrchypark** [comment] 2017-08-29 06:18
I find out package like [airflow](https://github.com/apache/incubator-airflow) or [luigi](https://github.com/spotify/luigi) for R language. drake is amazingly fit-package for my purpose but is not for manage pipeline for distributed jobs. Do you know some r packages like this?

**Comment by wlandau-lilly** [comment] 2017-08-29 12:52
Thanks for the pointers. Drake does not manage distributed jobs in the same way as airflow or luigi, but it does have distributed computing functionality. The idea is to hack `make -j` to send `Makefile` targets to different jobs on a cluster. From the end of the high-performance computing section in the [quickstart vignette]():

`make(my_plan, parallelism = "Makefile", jobs = 2, prepend = "SHELL=./shell.sh")` is similar [to plain `Makefile` parallelism], but it uses a helper file `shell.sh` to distribute the R sessions over different jobs/nodes on a cluster. Your `shell.sh` file should look something like the following, and you can use `shell_file()` to write an example.

> ```{r binbash, eval = FALSE}
> #!/bin/bash
> shift
> echo "module load R; $*" | qsub -sync y -cwd -j y
> ```
> 
> You may need to replace `module load R` with a command to load a specific version of R. [SLURM](https://slurm.schedmd.com/) users can just point to `srun` and dispense with `shell.sh` altogether.
> 
> ```{r cluster, eval = FALSE}
> make(my_plan, parallelism = "Makefile", jobs = 4,
>   prepend = "SHELL=srun")
> ```
> 
> For long projects, put your call to `make()` in an R script (say, `script.R`) and run it from the [Linux terminal](https://www.howtogeek.com/140679/beginner-geek-how-to-start-using-the-linux-terminal/).
> 
> ```{r nohup, eval = FALSE}
> nohup nice -19 R CMD BATCH script.R &
> ```
> 
> Even after you log out, a background process will keep running on the login node and submit new jobs at the appropriate time. Jobs are only submitted if the targets need to be (re)built.

I do have plans to add different forms of parallelism, including Hadoop and Spark (see #42). And it sounds like there is a lot more to learn from airflow and luigi.

**Comment by wlandau-lilly** [comment] 2017-09-16 16:51
Closing in favor of #42 because adding Docker parallelism should solve this.

**Comment by wlandau-lilly** [comment] 2017-10-20 19:54
I am reopening this one because I think we should solve it two different ways. One way is with #42: the `future` package can leverage Docker through a PSOCK cluster, which opens up job-monitoring functionality. But it would be nice to also have optional timeouts and retries with light-weight parallelism too. This has been in the back of my mind for the last two months, and the implementation no longer seems difficult.

1. Add new `timeout` and `retry` arguments to `make()` and `build_config()`.
1. Add new `timeout` and `retry` entries in the internal `config` list.
1. Define new `timeout()` and `retry()` functions that each do the nominal thing. Use specialized console messages for each using [finish_console()](https://github.com/wlandau-lilly/drake/blob/63289527b487b11ed4f50c8eb24cf1c1ce149687/R/console.R#L49) and appropriate [colors](https://github.com/wlandau-lilly/drake/blob/63289527b487b11ed4f50c8eb24cf1c1ce149687/R/color.R#L4) (red for timeouts, `green3` for retries).
1. Integrate `timeout()` and `retry()` into [build_target()](https://github.com/wlandau-lilly/drake/blob/63289527b487b11ed4f50c8eb24cf1c1ce149687/R/build.R#L28):

```r
build_target <- function(target, hashes, config) {
  command <- get_command(target = target, config = config) %>%
    functionize
  seed <- list(seed = config$seed, target = target) %>%
    seed_from_object
  withr::with_seed(seed, {
    retry({
      timeout({
        value <- eval(parse(text = command), envir = config$envir)
      }, timeout = config$timeout)
    }, retry = config$retry)
  })
  check_built_file(target)
  value
}
```

**Comment by wlandau-lilly** [comment] 2017-10-20 19:56
@AlexAxthelm and @mrchypark, do you think `withr::with_seed()` should go inside or outside `retry()`? I have mixed feelings on this point.

**Comment by wlandau-lilly** [comment] 2017-10-21 00:00
Maybe we should make use of `R.utils::withTimeout()` (HenrikBengtsson/future#169).

**Closed** 2017-10-22 06:35 UTC
Labels: enhancement

**Comment by wlandau-lilly** [comment] 2017-10-22 12:53
I have now implemented timeouts and retries, so I will consider this issue closed once the PR is merge. @mrchypark, feel free to open if you think there is something else we should add.

Demo:

```r
install_github("wlandau-lilly/drake") # Only in the dev version for now
library(drake)
random_sleep <- function(){
  time <- runif(1, min = 0, max = 1)
  Sys.sleep(time)
}
testplan <- plan(tmp = random_sleep())
set.seed(2017)
make(testplan, timeout = 0.1, retries = 200)
```

```r
## check 2 items: runif, Sys.sleep
## import runif
## import Sys.sleep
## check 1 item: random_sleep
## import random_sleep
## check 1 item: tmp
## target tmp
## timeout tmp [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## retry tmp: 1 of 200
## timeout tmp [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## retry tmp: 2 of 200
## timeout tmp [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## retry tmp: 3 of 200
## timeout tmp [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## retry tmp: 4 of 200
## timeout tmp [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## retry tmp: 5 of 200
## timeout tmp [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## retry tmp: 6 of 200
## timeout tmp [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## retry tmp: 7 of 200
## timeout tmp [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## retry tmp: 8 of 200
```

**Comment by wlandau-lilly** [comment] 2017-10-22 13:43
Hmm... It seems `R.utils::evalWithTimeout({Sys.sleep(1e6)}, timeout = 0.001)` does not interrupt `Sys.sleep()`. @HenrikBengtsson, do you happen to know why? @mrchypark, for a demo on timeouts and retries, try this instead.

```r
forever <- function() {
  while(1){1+1}
}
x <- plan(y = forever())
make(x, timeout = 0.1, retries = 2)
```

```r
## check 1 item: forever
i## mport forever
## check 1 item: y
## target y
## Error in catch_timeout(e, target = target, config = config) : 
##   reached CPU time limit
## retry y: 1 of 2
## timeout y [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## retry y: 2 of 2
## timeout y [cpu=0.1s, elapsed=0.1s]
## Error in catch_timeout(e, target = target, config = config) : 
##   reached elapsed time limit [cpu=0.1s, elapsed=0.1s]
## fail y
## Error in declare_failure(target = target, config = config) : 
##   Target y failed.
## No traceback available.
## To debug, use debug() on one of your functions or call make() with browser() in the appropriate workflow plan command.
```

**Comment by HenrikBengtsson** [comment] 2017-10-23 00:36
About `withTimeout(Sys.sleep(...))`, see Issue https://github.com/HenrikBengtsson/R.utils/issues/77.

**Comment by AlexAxthelm** [comment] 2017-10-23 13:14
[Re: with_seed()](https://github.com/wlandau-lilly/drake/issues/76#issuecomment-338307166): Looking at the PR, I think I would be inclined to put `with_seed()` inside of `with_retries()`. As it is now, the seed would be set once, and then if any of the tries touched the RNG, `.RandomSeed` would be different for each try. I've added a [comment inline in the PR.](https://github.com/wlandau-lilly/drake/commit/fd6fdb416b7b95c6a34fdd621d78fd7e258057f0#commitcomment-25133232)

**Comment by wlandau-lilly** [comment] 2017-10-23 13:20
Thanks, that makes sense. I just committed the change.

**Comment by wlandau-lilly** [comment] 2017-11-07 06:00
FYI: I added a whole new ["debug" vignette](https://github.com/wlandau-lilly/drake/blob/master/vignettes/debug.Rmd) vignette with [a section on timeouts and retries](https://github.com/wlandau-lilly/drake/blob/master/vignettes/debug.Rmd#impose-timeouts-and-retries). @mrchypark thank you again for suggesting the feature.
