### ISSUE TITLE
manually add objects to the cache?

### ISSUE THREAD

**Issue by pat-s** [wlandau-lilly/drake#194] opened 2018-01-22 21:09 UTC
In my case I have several long running jobs that run ~ 2 weeks combined and would only need to be rebuild for `drake`.

It would be great if an option exists that one can manually add a saved file (`.rda`, `.rds`) to the cache so that an existing step does not need to be rebuild when setting up a plan.

Assuming the outcome of the following step does already exist on the system:

```r
analyze <- drake_plan(
  [...]
  brt_sp_non.md = knit('03_scripts/server/brt_sp_non.Rmd', quiet = TRUE)
  [...]
```

It would be great if one could do something like

`drake::add_to_cache(brt_sp_non.md = brt_sp_non.Rmd)`

In this case, instead of a full rebuild,  `drake` would just scan the file for dependencies and store the configuration so that `drake` can detect a possible file change in the future.

**Comment by wlandau-lilly** [comment] 2018-01-23 02:30
If you have a dataset you want to transfer over to a `drake` workflow, you can treat it as an imported file. Suppose your old computations returned a dataset that you saved to a file called `valuable_data.rds`. You spent 2 weeks computing it, and now you want to reuse it in a new `drake` project. You could do something like this.

```r
analyze <- drake_plan(
  valuable_data = readRDS('valuable_data.rds'),
  intermediate_result = long_running_function(valuable_data),
  final_result = as.data.frame(make_a_matrix(intermediate_result))
)

config <- drake_config(analyze)
vis_drake_graph(config)
```

![hypo](https://user-images.githubusercontent.com/22958003/35255065-1f1c4882-ffbb-11e7-9871-65323756574d.png)

In this workflow, `valuable_data.rds` begins as an imported file, and the target `valuable_data` is the contents of the file. Your previous work is now a starting place for `drake`.

**Comment by wlandau-lilly** [comment] 2018-01-23 15:25
As far as manually adding to the cache with a function like `add_to_cache()`, I foresee problems. Targets in the cache have lots of accompanying metadata to link them with their dependencies. This is important for maintaining a reproducible pipeline. The objects and metadata should not be modified manually because the results must stay faithful to the code and commands that generated them.

I think I understand this issue and I think I have addressed it, so I am closing it. But if you have more questions, let's definitely keep talking.

**Closed by wlandau-lilly** 2018-01-23 15:25 UTC
Labels: question
